#! /bin/sh

xsetroot -cursor_name left_ptr

# auto start
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/myScript/setcard.sh
$HOME/.config/polybar/forest/launch.sh
picom -b
feh --bg-fill $HOME/Downloads/wallpaper1.jpg
fcitx5 &
ps aux | grep -v grep | grep care_eye || $HOME/myScript/careEye/start_care_eye.sh
optimus-manager-qt &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config normal_border_color		      "#579da0"
# bspc config focused_border_color	      "#CE93D8"
bspc config focused_border_color	      "#ffb0cd"

# bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
# bspc config initial_polarity first_child
# bspc config automatic_scheme spiral
# bspc config automatic_scheme longest_side

bspc rule -a Gimp-2.10 desktop='^3' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a EasyConnect state=floating

sleep 3
# Terminate already running klipper instances
killall -q klipper
# Wait until the processes have been shut down
while pgrep -u $UID -x klipper >/dev/null; do sleep 1; done
klipper &
